all:
	@echo "INFO: make <TAB> for targets"
.PHONY: all

clean:
	@rm -f *.npy *.png *.log *.jou
	@rm -rf hls/*prj
	@rm -rf hls/*gz
	@rm -rf npy
	@rm -rf model
	@rm -rf hls4ml_prj*
	@rm -rf .ipynb_checkpoints
	@rm -rf __pycache__
	@rm -rf Packages
.PHONY: clean
